// ==UserScript==
// @name         NTUH 登入助手
// @namespace    http://tampermonkey.net/
// @version      6.0
// @icon         https://www.ntuh.gov.tw/images/logo.ico
// @description  Recognize the NTUH Portal captcha and provide opt-in quick login for saved accounts.
// @author       WeiJyun9008
// @match        https://portal.ntuh.gov.tw/General/Login.aspx*
// @updateURL    https://github.com/Twb06/NTUH-helper/raw/refs/heads/main/scripts/login-helper.user.js
// @downloadURL  https://github.com/Twb06/NTUH-helper/raw/refs/heads/main/scripts/login-helper.user.js
// @grant        none
// @run-at       document-end
// ==/UserScript==

// Generated by tools/build-login-helper.js. Edit scripts/src/login-helper.user.js or scripts/lib/login-ocr.js.

(() => {
    "use strict";

    const TEMPLATE_PACKED = {
        "1": [9, 22, "Dg8Pn8/n8/g8Hg8Hg8Hg8Hg8Hg8//////A=="],
        "2": [14, 21, "D+D/5/+/H/g/gPADwB4A+AfAfgPwPwDwB4A8APADwA//v////A=="],
        "3": [14, 23, "D4D/h/8f/nh5wOADgD4P+H/B/gP8AfgB4APAD+A/gP8H//5/8P+B/AA="],
        "4": [17, 22, "ADwAPgAfAB+AH8Af4A/wD7gPnAeOB4cHx4f/+/////7//wA+AA4ABwADgAHAAOA="],
        "5": [15, 23, "//3/+//3/88AHgA/+H/8//3/++D3gP4B4APAB4APAD3Ae8P3/8//D/wH4AA="],
        "6": [14, 22, "AcAPAHwD4B8A+AfAHwD/4//v/74f8D+AfgH4B/A/wPfP3/4/8H8A"],
        "7": [17, 23, "//9/////3//gA+AD4AHgAfAB8ADwAHgAeAA8AD4AHgAPAA8AB4AHwAPAAeAA4ABwAA=="],
        "8": [15, 23, "B/A/8P/x/+fDzwOeDz4+P/w/8P/x/+fH7wP8B/gH8B/wPfD7//P/w/8B+AA="],
        "9": [16, 23, "B+Af+D/8f/74PvAe8A/wD/AP+B78fn/+P/4f/gf8AHwA+AH4D/A/4H+AfgA4AA=="],
        "B": [16, 22, "f8D/8P/48PjwPPA88DzwfP/4//j/+P/88HzwPvAe8A/wHvB+8fz/+P/wfwA="],
        "D": [18, 23, "MAAfAAf4Af+Af/gcfwcH4cB8cA+cAecAOcAPcAPcAPcAPcAPcAf8A+8B+//8//4f/wH/AA=="],
        "F": [16, 23, "f/x//n//f/5wAHAAcABwAP/8f/x//H/4eABwAHAAcABwAHAAcABwAHAAcABgAA=="],
        "H": [19, 23, "cABuAB/AB/gA/wAf4AP8AH+AD/AB/h////////////8H/AB/gA7wAf4AP8AH8AD+AB/AA/gAcA=="],
        "J": [18, 24, "D/+D/+D//D/+AHwAHgAHgAHgAHgAHgAHgAHgAHgAHgAHgYHg8Hg8HA8HA/HAf/AP+AH+AB8A"],
        "L": [15, 23, "cADgAcADgAcADgAcADgAcADgAcADgAcAHgA8AHgA8AHgA8D3///////f+AA="],
        "N": [21, 24, "4AB3gAe+AD3wAe/AB38AO/wB3+AP/4B3PgP8+B3D4P4fh3h+O4Hx3AfO4B/3gH+4Af3gB+4AH3AAe4ABnAAA"],
        "P": [14, 22, "f4H/h/8efnB/wP8D/A/we+fv/z/4/8PADgA8APADwA4APADgA4AA"],
        "R": [16, 22, "/gD/wP/w8/jg+OA84D7gHuAe4B7gPPD8//j/4P/g//Dj+OD84H7gP+AP4A4="],
        "T": [20, 22, "f/////9///AfAADgAA8AAPAADwAA8AAPAADwAA8AAPAADwAA8AAPAADwAAcAAHAABwAAcAAHAA=="],
        "V": [18, 22, "cAO8AP8AfcAeeA8eA8eA8PB4PB4PD4HjwHjwHngHngD/gD/AD/AB+AB+AB+AA8AA4AA="],
        "X": [19, 23, "YAD+AD/gD74B8+B8Ph8Dx8B88Af+AH+AB+AA+AA/gAf4Af8AfPAfHwfB8fAefAPvAD/AA/AAMA=="],
        "Z": [20, 23, "f//H//9///f//gAPwAH4AD4AB8AA+AAPAAHwAD4AB8AAeAAPgAHwAB4AA8AAfAAH//7//+f//3//4A=="]
    };

    let templates;

    function loadTemplates() {
        templates ??= Object.entries(TEMPLATE_PACKED).map(([char, [w, h, b64]]) => {
            const str = atob(b64), data = new Uint8Array(w * h);
            let cnt = 0, bit = 0;
            for (let i = 0; i < str.length; i++) {
                for (let b = 7; b >= 0 && bit < data.length; b--, bit++) {
                    if ((str.charCodeAt(i) >> b) & 1) {
                        data[bit] = 1;
                        cnt++;
                    }
                }
            }
            return { char, w, h, data, cnt };
        });
        return templates;
    }

    function trimSegment(segment) {
        let minX = segment.w, maxX = -1, minY = segment.h, maxY = -1;
        for (let y = 0; y < segment.h; y++) {
            for (let x = 0; x < segment.w; x++) {
                if (!segment.data[y * segment.w + x]) continue;
                if (x < minX) minX = x;
                if (x > maxX) maxX = x;
                if (y < minY) minY = y;
                if (y > maxY) maxY = y;
            }
        }
        if (maxX < 0) return null;

        const width = maxX - minX + 1;
        const height = maxY - minY + 1;
        const data = new Uint8Array(width * height);
        for (let y = 0; y < height; y++) {
            for (let x = 0; x < width; x++) {
                data[y * width + x] = segment.data[(y + minY) * segment.w + (x + minX)];
            }
        }
        return { left: segment.left + minX, w: width, h: height, data };
    }

    function splitMergedSegment(segments) {
        if (segments.length !== 5) return;

        const largestIndex = segments.reduce((max, segment, index, all) =>
            segment.w * segment.h > all[max].w * all[max].h ? index : max, 0);
        const segment = segments[largestIndex];
        let bestColumn = 1, minimumPixels = Infinity;

        for (let x = 1; x < segment.w - 1; x++) {
            let count = 0;
            for (let y = 0; y < segment.h; y++) {
                if (segment.data[y * segment.w + x]) count++;
            }
            if (count < minimumPixels) {
                minimumPixels = count;
                bestColumn = x;
            }
        }

        const leftData = new Uint8Array(segment.w * segment.h);
        const rightData = new Uint8Array(segment.w * segment.h);
        for (let y = 0; y < segment.h; y++) {
            for (let x = 0; x < segment.w; x++) {
                if (segment.data[y * segment.w + x]) {
                    (x < bestColumn ? leftData : rightData)[y * segment.w + x] = 1;
                }
            }
        }

        const left = trimSegment({ left: segment.left, w: segment.w, h: segment.h, data: leftData });
        const right = trimSegment({ left: segment.left, w: segment.w, h: segment.h, data: rightData });
        if (left && right) segments.splice(largestIndex, 1, left, right);
    }

    function extractSegments(binary, width, height) {
        const indexOf = (x, y) => y * width + x;

        for (let y = 1; y < height - 1; y++) {
            for (let x = 1; x < width - 1; x++) {
                const index = indexOf(x, y);
                if (!binary[index]) continue;
                let neighbours = 0;
                for (let dy = -1; dy <= 1; dy++) {
                    for (let dx = -1; dx <= 1; dx++) {
                        if ((dx || dy) && binary[indexOf(x + dx, y + dy)]) neighbours++;
                    }
                }
                if (neighbours <= 1) binary[index] = 0;
            }
        }

        const visited = new Uint8Array(width * height);
        const segments = [];
        for (let y = 0; y < height; y++) {
            for (let x = 0; x < width; x++) {
                const start = indexOf(x, y);
                if (visited[start] || !binary[start]) continue;

                const stack = [start], pixels = [];
                visited[start] = 1;
                while (stack.length) {
                    const pixel = stack.pop();
                    pixels.push(pixel);
                    const currentX = pixel % width;
                    const currentY = Math.floor(pixel / width);

                    for (let dy = -1; dy <= 1; dy++) {
                        for (let dx = -1; dx <= 1; dx++) {
                            const nextX = currentX + dx, nextY = currentY + dy;
                            if (nextX < 0 || nextX >= width || nextY < 0 || nextY >= height) continue;
                            const next = indexOf(nextX, nextY);
                            if (!visited[next] && binary[next]) {
                                visited[next] = 1;
                                stack.push(next);
                            }
                        }
                    }
                }

                if (pixels.length < 25) continue;
                let minX = width, maxX = 0, minY = height, maxY = 0;
                for (const pixel of pixels) {
                    const currentX = pixel % width, currentY = Math.floor(pixel / width);
                    if (currentX < minX) minX = currentX;
                    if (currentX > maxX) maxX = currentX;
                    if (currentY < minY) minY = currentY;
                    if (currentY > maxY) maxY = currentY;
                }
                const segmentWidth = maxX - minX + 1;
                const segmentHeight = maxY - minY + 1;
                const data = new Uint8Array(segmentWidth * segmentHeight);
                for (const pixel of pixels) {
                    data[(Math.floor(pixel / width) - minY) * segmentWidth + (pixel % width - minX)] = 1;
                }
                segments.push({ left: minX, w: segmentWidth, h: segmentHeight, data });
            }
        }

        segments.sort((a, b) => a.left - b.left);
        splitMergedSegment(segments);
        return segments;
    }

    function matchSegment(segment) {
        let bestCharacter = "?", bestScore = -1;
        const segmentPixels = segment.data.reduce((sum, value) => sum + value, 0);

        for (const template of loadTemplates()) {
            const centerX = Math.round((segment.w - template.w) / 2);
            const centerY = Math.round((segment.h - template.h) / 2);
            for (let offsetY = centerY - 3; offsetY <= centerY + 3; offsetY++) {
                for (let offsetX = centerX - 3; offsetX <= centerX + 3; offsetX++) {
                    let intersection = 0;
                    for (let y = Math.max(0, offsetY), endY = Math.min(segment.h, offsetY + template.h); y < endY; y++) {
                        for (let x = Math.max(0, offsetX), endX = Math.min(segment.w, offsetX + template.w); x < endX; x++) {
                            if (segment.data[y * segment.w + x] && template.data[(y - offsetY) * template.w + (x - offsetX)]) {
                                intersection++;
                            }
                        }
                    }
                    const score = intersection / (segmentPixels + template.cnt - intersection);
                    if (score > bestScore) {
                        bestScore = score;
                        bestCharacter = template.char;
                    }
                }
            }
        }
        return bestCharacter;
    }

    function recognizeCaptcha(image) {
        const width = image.naturalWidth, height = image.naturalHeight;
        if (!width || !height) return null;

        const canvas = document.createElement("canvas");
        canvas.width = width;
        canvas.height = height;
        const context = canvas.getContext("2d", { willReadFrequently: true });
        context.drawImage(image, 0, 0);

        const pixels = context.getImageData(0, 0, width, height).data;
        const binary = new Uint8Array(width * height);
        for (let i = 0, pointer = 0; i < width * height; i++, pointer += 4) {
            const red = pixels[pointer], green = pixels[pointer + 1], blue = pixels[pointer + 2];
            binary[i] = red * 77 + green * 150 + blue * 29 < 32000 ? 1 : 0;
        }

        const text = extractSegments(binary, width, height).slice(0, 6).map(matchSegment).join("");
        return text.length === 6 && !text.includes("?") ? text : null;
    }

    globalThis.NTUHLoginOCR = Object.freeze({ recognizeCaptcha });
})();

(() => {
    "use strict";

    const CREDENTIALS_KEY = "ntuh-login-credentials-v2";
    const LEGACY_CREDENTIAL_KEY = "ntuh-login-credential-v1";
    const OCR_FAILURES_KEY = "ntuh-login-ocr-failures-v1";
    const MAX_AUTO_REFRESHES = 3;

    let passwordHashToBypassOnce = null;
    let expressLoginPending = false;

    function isCredential(value) {
        return Boolean(value) && typeof value.user === "string" && value.user.length > 0 &&
            typeof value.passMD5 === "string" && value.passMD5.length > 0;
    }

    function loadCredentials() {
        let credentials = [];

        try {
            const saved = JSON.parse(localStorage.getItem(CREDENTIALS_KEY));
            if (Array.isArray(saved)) {
                credentials = saved.filter(isCredential).filter((credential, index, all) =>
                    all.findIndex(item => item.user === credential.user) === index);
            }
        } catch (error) {
            console.warn("Unable to load saved NTUH credentials:", error);
        }

        try {
            const legacy = JSON.parse(localStorage.getItem(LEGACY_CREDENTIAL_KEY));
            if (isCredential(legacy) && !credentials.some(item => item.user === legacy.user)) {
                credentials.push(legacy);
            }
            if (isCredential(legacy)) {
                localStorage.setItem(CREDENTIALS_KEY, JSON.stringify(credentials));
                localStorage.removeItem(LEGACY_CREDENTIAL_KEY);
            }
        } catch (error) {
            console.warn("Unable to migrate the legacy NTUH credential:", error);
        }

        return credentials;
    }

    function storeCredentials(credentials) {
        localStorage.setItem(CREDENTIALS_KEY, JSON.stringify(credentials));
    }

    function saveCredential(user, passMD5) {
        const credentials = loadCredentials().filter(item => item.user !== user);
        storeCredentials([{ user, passMD5 }, ...credentials]);
    }

    function removeCredential(user) {
        storeCredentials(loadCredentials().filter(item => item.user !== user));
    }

    function injectStyles() {
        const style = document.createElement("style");
        style.textContent = `
            #ntuhQuickLoginAccounts {
                display: grid;
                grid-template-columns: repeat(2, minmax(0, 1fr));
                gap: 4px;
                width: 164px;
            }
            .ntuhQuickLoginCard {
                display: flex;
                min-width: 0;
                height: 24px;
                overflow: hidden;
                color: inherit;
                background: #f5f5f5;
                border: 1px solid #999;
            }
            .ntuhQuickLoginButton,
            .ntuhQuickLoginDelete {
                padding: 0;
                color: inherit;
                background: transparent;
                border: 0;
                cursor: pointer;
                font: inherit;
            }
            .ntuhQuickLoginButton {
                flex: 1;
                min-width: 0;
                padding-left: 5px;
                overflow: hidden;
                text-align: left;
                text-overflow: ellipsis;
            }
            .ntuhQuickLoginDelete {
                width: 20px;
                color: #777;
                border-left: 1px solid #bbb;
                font-size: 14px;
            }
            .ntuhQuickLoginButton:hover { background: #e8e8e8; }
            .ntuhQuickLoginDelete:hover { color: #a00000; background: #f2dddd; }
            #ntuhRememberLoginLabel { white-space: nowrap; }
            #ntuhCaptchaDetails { width: 164px; }
            #ntuhCaptchaDetails > summary {
                width: max-content;
                color: inherit;
                cursor: pointer;
            }
            #ntuhCaptchaManualContent { margin-top: 5px; }
            #ntuhCaptchaManualContent #lblVerifyMsg { display: none; }
            #ntuhCaptchaManualContent #txtVerifyCode {
                display: block;
                margin-top: 5px;
            }
        `;
        document.head.appendChild(style);
    }

    function createLoginRow(labelText, id) {
        const row = document.createElement("tr");
        const labelCell = document.createElement("td");
        const controlCell = document.createElement("td");

        row.id = id;
        labelCell.className = "LogIn";
        labelCell.align = "right";
        labelCell.style.whiteSpace = "nowrap";
        labelCell.textContent = labelText;
        controlCell.className = "LogIn";
        controlCell.align = "left";
        row.append(labelCell, controlCell);
        return { row, controlCell };
    }

    function addRememberCheckbox(passwordRow) {
        const { row, controlCell } = createLoginRow("", "ntuhRememberLoginRow");
        const label = document.createElement("label");
        const checkbox = document.createElement("input");

        label.id = "ntuhRememberLoginLabel";
        checkbox.id = "ntuhRememberLogin";
        checkbox.type = "checkbox";
        label.append(checkbox, " 記住我的帳號");
        controlCell.appendChild(label);
        passwordRow.insertAdjacentElement("afterend", row);
        return checkbox;
    }

    function renderQuickLoginCards(accountRow, onLogin) {
        document.getElementById("ntuhQuickLoginRow")?.remove();
        const credentials = loadCredentials();
        if (credentials.length === 0) return;

        const { row, controlCell } = createLoginRow("快速登入", "ntuhQuickLoginRow");
        const accounts = document.createElement("div");
        accounts.id = "ntuhQuickLoginAccounts";

        for (const credential of credentials) {
            const card = document.createElement("div");
            const login = document.createElement("button");
            const remove = document.createElement("button");

            card.className = "ntuhQuickLoginCard";
            login.type = "button";
            login.className = "ntuhQuickLoginButton";
            login.textContent = credential.user;
            login.title = `以 ${credential.user} 快速登入`;
            login.addEventListener("click", () => onLogin(credential));

            remove.type = "button";
            remove.className = "ntuhQuickLoginDelete";
            remove.textContent = "×";
            remove.title = `移除 ${credential.user}`;
            remove.setAttribute("aria-label", `移除 ${credential.user}`);
            remove.addEventListener("click", () => {
                if (!confirm(`確定移除帳號 ${credential.user}？`)) return;
                removeCredential(credential.user);
                renderQuickLoginCards(accountRow, onLogin);
            });

            card.append(login, remove);
            accounts.appendChild(card);
        }

        controlCell.appendChild(accounts);
        accountRow.insertAdjacentElement("beforebegin", row);
    }

    function addCaptchaDisclosure(captchaImageRow, captchaInputRow, input) {
        const { row, controlCell } = createLoginRow("驗證碼", "ntuhCaptchaDisclosureRow");
        const details = document.createElement("details");
        const summary = document.createElement("summary");
        const content = document.createElement("div");
        const originalContent = captchaImageRow.querySelector("td > div");

        details.id = "ntuhCaptchaDetails";
        summary.textContent = "手動輸入";
        content.id = "ntuhCaptchaManualContent";
        if (originalContent) content.appendChild(originalContent);
        content.appendChild(input);
        details.append(summary, content);
        controlCell.appendChild(details);
        captchaImageRow.insertAdjacentElement("beforebegin", row);
        captchaImageRow.style.display = "none";
        captchaInputRow.style.display = "none";
        return { row, details };
    }

    function removeHiddenCapsLockSpacing(status) {
        if (!status) return;

        const syncDisplay = () => {
            status.toggleAttribute("hidden", status.style.visibility === "hidden");
        };

        new MutationObserver(syncDisplay).observe(status, {
            attributes: true,
            attributeFilter: ["style"]
        });
        syncDisplay();
    }

    function installCredentialCapture(rememberCheckbox, afterSave) {
        const original = window.CheckAndSetPassTextBox;
        if (typeof original !== "function") return false;

        window.CheckAndSetPassTextBox = function(textboxID) {
            if (textboxID === "txtPass" && passwordHashToBypassOnce !== null) {
                const currentPassword = document.querySelector("#txtPass")?.value;
                const shouldBypass = currentPassword === passwordHashToBypassOnce;
                passwordHashToBypassOnce = null;
                if (shouldBypass) return;
            }

            const result = original.apply(this, arguments);
            if (textboxID === "txtPass" && rememberCheckbox.checked) {
                const user = document.querySelector("#txtUserID")?.value.trim();
                const passMD5 = document.querySelector("#txtPass")?.value;
                if (user && passMD5) {
                    saveCredential(user, passMD5);
                    afterSave();
                }
            }
            return result;
        };
        return true;
    }

    function readFailureCount() {
        const value = Number.parseInt(sessionStorage.getItem(OCR_FAILURES_KEY), 10);
        return Number.isFinite(value) ? value : 0;
    }

    function init() {
        const ocr = globalThis.NTUHLoginOCR;
        const user = document.querySelector("#txtUserID");
        const pass = document.querySelector("#txtPass");
        const capsLockStatus = document.getElementById("capStatus");
        const accountRow = user?.closest("tr");
        const passwordRow = pass?.closest("tr");
        const captchaImageRow = document.getElementById("tr_p_2");
        const captchaInputRow = document.getElementById("tr_p_3");
        const image = document.querySelector("img#imgVerifyCode");
        const input = document.querySelector("input#txtVerifyCode");
        const refresh = document.querySelector("#ibnRegenVerifyImg");
        const submit = document.getElementById("imgBtnSubmitNew");

        if (!ocr || !user || !pass || !accountRow || !passwordRow ||
            !captchaImageRow || !captchaInputRow || !image || !input || !refresh || !submit) return;

        injectStyles();
        removeHiddenCapsLockSpacing(capsLockStatus);
        const rememberCheckbox = addRememberCheckbox(passwordRow);
        const captchaDisclosure = addCaptchaDisclosure(captchaImageRow, captchaInputRow, input);

        const submitExpressLogin = () => {
            if (!expressLoginPending || input.value.trim().length !== 6) return;
            expressLoginPending = false;
            submit.click();
        };

        const revealManualCaptcha = () => {
            captchaDisclosure.details.open = true;
            input.focus();
        };

        const handleRecognitionFailure = () => {
            const failures = readFailureCount() + 1;
            sessionStorage.setItem(OCR_FAILURES_KEY, String(failures));
            if (failures >= MAX_AUTO_REFRESHES) {
                revealManualCaptcha();
                return;
            }
            refresh.click();
        };

        const recognize = () => {
            try {
                const text = ocr.recognizeCaptcha(image);
                if (!text) {
                    handleRecognitionFailure();
                    return;
                }
                sessionStorage.removeItem(OCR_FAILURES_KEY);
                input.value = text;
                submitExpressLogin();
            } catch (error) {
                console.error("Template OCR error:", error);
                handleRecognitionFailure();
            }
        };

        const loginWithCredential = credential => {
            user.value = credential.user;
            pass.value = credential.passMD5;
            passwordHashToBypassOnce = credential.passMD5;
            expressLoginPending = true;
            if (input.value.trim().length === 6) submitExpressLogin();
            else if (image.complete && image.naturalWidth) recognize();
        };

        const renderAccounts = () => renderQuickLoginCards(accountRow, loginWithCredential);
        const passwordHookInstalled = installCredentialCapture(rememberCheckbox, renderAccounts);
        if (!passwordHookInstalled) console.warn("CheckAndSetPassTextBox() is unavailable; quick login is disabled.");
        else renderAccounts();

        pass.addEventListener("keydown", event => {
            if (event.key === "Enter") submit.click();
        });

        const verification = document.getElementById("ddl_verification");
        const updatePasswordOnlyRows = () => {
            const visible = !verification || verification.value === "P";
            document.getElementById("ntuhQuickLoginRow")?.toggleAttribute("hidden", !visible);
            document.getElementById("ntuhRememberLoginRow")?.toggleAttribute("hidden", !visible);
            captchaDisclosure.row.toggleAttribute("hidden", !visible);
            captchaImageRow.style.display = "none";
            captchaInputRow.style.display = "none";
        };
        verification?.addEventListener("change", () => setTimeout(updatePasswordOnlyRows));
        updatePasswordOnlyRows();

        if (readFailureCount() >= MAX_AUTO_REFRESHES) revealManualCaptcha();

        image.crossOrigin = "anonymous";
        image.onload = recognize;
        if (image.complete && image.naturalWidth) recognize();
    }

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", init);
    } else {
        init();
    }
})();
